#!/bin/bash

if [[ $LAST_COMMIT_MESSAGE = *"skip sync"* ]]; then
    echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
    echo "SKIPPING STATIC ASSETS SYNC"
    echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
    exit 0
fi

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Install NPM"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
yum -y install nodejs
npm -v

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Install Grunt"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

npm install -g grunt-cli

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Installing Node packages"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

npm install

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Running grunt to compile css and js"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

grunt

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Syncing static files to s3 bucket"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

s3_buckets=()
if [ "$BITBUCKET_BRANCH" == "uat" ]
then
    s3_buckets=(aif-staging-static)
fi

for bucket in ${s3_buckets[*]}
do

    ##############################################
    #   AIF ADMIN STATIC SYNC
    ##############################################
if [[ $LAST_COMMIT_MESSAGE = *"sync admin"* ]]; then

    echo "######################################"
    echo "ADMIN: " `date +'%H:%M:%S'`
    echo "######################################"

    aws s3 sync frontend/web/static/admin/dist/deploy/ s3://$bucket/static/admin/dist/deploy --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/dev/ s3://$bucket/static/admin/dev --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/fonts/ s3://$bucket/static/admin/fonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/images/ s3://$bucket/static/admin/images --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/webfonts/ s3://$bucket/static/admin/webfonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/dev/ s3://$bucket/static/admin/dev --quiet --delete --acl "public-read" --cache-control max-age=604800
fi
    
    
##############################################
#   AIF STATIC SYNC
##############################################
if [[ $LAST_COMMIT_MESSAGE = *"sync website"* ]]; then
   
   echo "######################################"
    echo "Website: " `date +'%H:%M:%S'`
    echo "######################################"

    aws s3 sync frontend/web/static/dist/deploy/ s3://$bucket/static/dist/deploy --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/dist/fonts/ s3://$bucket/static/dist/fonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/dist/images/ s3://$bucket/static/dist/images --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/dist/favicon/ s3://$bucket/static/dist/favicon --quiet --delete --acl "public-read" --cache-control max-age=604800
fi

    echo "######################################"
    echo "ADMIN: " `date +'%H:%M:%S'`
    echo "######################################"

    aws s3 sync frontend/web/static/admin/dist/ s3://$bucket/static/admin/dist --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/dev/ s3://$bucket/static/admin/dev --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/fonts/ s3://$bucket/static/admin/fonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/images/ s3://$bucket/static/admin/images --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/webfonts/ s3://$bucket/static/admin/webfonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    aws s3 sync frontend/web/static/admin/dev/ s3://$bucket/static/admin/dev --quiet --delete --acl "public-read" --cache-control max-age=604800


    echo "######################################"
    echo "Website: " `date +'%H:%M:%S'`
    echo "######################################"

    # aws s3 sync frontend/web/static/dist/deploy/ s3://$bucket/static/dist/deploy --quiet --delete --acl "public-read" --cache-control max-age=604800
    # aws s3 sync frontend/web/static/dist/fonts/ s3://$bucket/static/dist/fonts --quiet --delete --acl "public-read" --cache-control max-age=604800
    # aws s3 sync frontend/web/static/dist/images/ s3://$bucket/static/dist/images --quiet --delete --acl "public-read" --cache-control max-age=604800
    # aws s3 sync frontend/web/static/dist/favicon/ s3://$bucket/static/dist/favicon --quiet --delete --acl "public-read" --cache-control max-age=604800

done


